services:
  redis:
    image: redis:alpine
    tty: true

  redis-admin:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - 8081:8081
    depends_on:
      - redis

  # app-alpine:
  #   build: ./docker/nim/alpine
  #   tty: true
  #   ports:
  #     - 9000:8000
  #   volumes:
  #     - .:/root/project

  app-ubuntu:
    build:
      context: .
      dockerfile: ./docker/nim/ubuntu/Dockerfile
      args:
        NIM_VERSION: 2.2.0
    tty: true
    ports:
      - 8000:8000
    volumes:
      - .:/root/project

  # app-debian:
  #   build:
  #     context: .
  #     dockerfile: ./docker/nim/debian/Dockerfile
  #     args:
  #       VERSION: 1.6.10
  #   tty: true
  #   ports:
  #     - 9000:8000
  #   volumes:
  #     - .:/root/project

  # app-centos:
  #   build:
  #     context: .
  #     dockerfile:./docker/nim/centos
  #     args:
  #       VERSION: 1.6.8
  #   tty: true
  #   privileged: true
  #   ports:
  #     - 9003:8000
  #   volumes:
  #     - .:/root/project

  # frontend:
  #   build:
  #     context: .
  #     dockerfile: ./docker/frontend/Dockerfile
  #     args:
  #       VERSION: 1.6.8
  #   tty: true
  #   ports:
  #     - 3000:3000
  #   volumes:
  #     - ./examples/todo_app.bk/frontend:/root/project

  mariaDb:
    image: mariadb
    tty: true
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      default_authentication_plugin: mysql_native_password

  postgreDb:
    image: postgres:alpine
    tty: true
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    command: postgres -c 'max_connections=2000'
