services:
  redis:
    image: redis:alpine
    tty: true

  basolato-test-ubuntu:
    build:
      context: .
      dockerfile: ./docker/nim/ubuntu/test.Dockerfile
      args:
        VERSION: 2.0.0
    tty: true
    volumes:
      - .:/root/project
