version: '3'
services:
  redis:
    image: redis:alpine
    tty: true

  app-ubuntu-v1:
    build:
      context: .
      dockerfile: ./docker/nim/ubuntu/Dockerfile
      args:
        VERSION: 1.6.18
    tty: true
    volumes:
      - .:/root/project

  app-ubuntu:
    build:
      context: .
      dockerfile: ./docker/nim/ubuntu/Dockerfile
      args:
        VERSION: 2.0.2
    tty: true
    volumes:
      - .:/root/project
