import unittest, tables, json
import ../src/basolato/validation

suite "email valid":
  test "strictEmail":
    let valid_addresses = [
      {"email": "email@domain.com"}.toTable(),
      {"email": "firstname.lastname@domain.com"}.toTable(),
      {"email": "email@subdomain.domain.com"}.toTable(),
      {"email": "firstname+lastname@domain.com"}.toTable(),
      {"email": "1234567890@domain.com"}.toTable(),
      {"email": "_______@domain.com"}.toTable(),
      {"email": "firstname-lastname@domain.com"}.toTable(),
      {"email": "-email@domain"}.toTable(),
      {"email": "abcABC123.defDEF456@ghiGHI789.comCOM012"}.toTable(),
      {"email": "abc.#%&'/=~`*+?{}^$-|@ghi.com"}.toTable(),
      {"email": "Abc@example.com"}.toTable(),
      {"email": "Abc.123@example.com"}.toTable(),
      {"email": "user+mailbox/department=shipping@example.com"}.toTable(),
      {"email": "customer/department=shipping@example.com"}.toTable(),
      {"email": "!#$%&'*+-/=?^_`.{|}~@example.com"}.toTable(),
      {"email": "!def!xyz%abc@example.com"}.toTable(),
      {"email": """"e#$$%&@>mail"@domain.com"""}.toTable(),
      {"email": """"em,ail"@localhost"""}.toTable(),
      {"email": """"Abc@def"@example.com"""}.toTable(),
      {"email": """"Fred\ Bloggs"@example.com"""}.toTable(),
      {"email": """"Joe.\\Blow"@example.com"""}.toTable(),
      {"email": """"Joe.\"Blow"@example.com"""}.toTable(),
      {"email": """".dot_kara_hazimaru"@example.com"""}.toTable(),
      {"email": """"I.likeyou."@example.com"""}.toTable(),
      {"email": """"I..love...you"@example.com"""}.toTable(),
      {"email": "email@domain-one.com"}.toTable(),
      {"email": "email@domain.co.jp"}.toTable(),
      {"email": "email@localhost"}.toTable(),
      {"email": "a@a"}.toTable(),
      {"email": "a@0.a"}.toTable(),
      {"email": "a@a-a.com"}.toTable(),
      {"email": "a@0-a.com"}.toTable(),
      {"email": "a@a-0.com"}.toTable(),
      {"email": "a@a-a.a-a"}.toTable(),
      # {"email": ""}.toTable(),
      # {"email": ""}.toTable(),
      # {"email": ""}.toTable(),
      # {"email": ""}.toTable(),
      # {"email": ""}.toTable(),
      # {"email": ""}.toTable(),
      # {"email": ""}.toTable(),
      # {"email": ""}.toTable(),
      # {"email": ""}.toTable(),
      # {"email": ""}.toTable(),
      # {"email": ""}.toTable(),
      # {"email": ""}.toTable(),
      # {"email": ""}.toTable(),
      # {"email": ""}.toTable(),
      # {"email": ""}.toTable(),
      # {"email": ""}.toTable(),
      # {"email": ""}.toTable(),
      # {"email": ""}.toTable(),
      # {"email": ""}.toTable(),
      # {"email": ""}.toTable(),
      # {"email": ""}.toTable(),
      # {"email": ""}.toTable(),
      # {"email": ""}.toTable(),
      # {"email": ""}.toTable(),
      # {"email": ""}.toTable(),
      # {"email": ""}.toTable(),
      # {"email": ""}.toTable(),
      # {"email": ""}.toTable(),
      # {"email": ""}.toTable(),
      # {"email": ""}.toTable(),
      # {"email": ""}.toTable(),
      # {"email": ""}.toTable(),
      # {"email": ""}.toTable(),
      # {"email": ""}.toTable(),
      # {"email": ""}.toTable(),
    ]

    for valid_address in valid_addresses:
      let v = Validation(params: valid_address,
                          errors: newJObject())
                        .strictEmail("email")
      check v.errors.len == 0

  test "strictEmail invalid":
    let valid_addresses = [
      {"email": "Abc.@example.com"}.toTable(),
      {"email": "Abc..123@example.com"}.toTable(),
      {"email": ".dot_kara_hazimaru@example.com"}.toTable(),
      {"email": "I.like.you.@example.com"}.toTable(),
      {"email": "I..love...you@example.com"}.toTable(),
      {"email": "abc.def@#%&'/=~`*+?{}^$-|.com"}.toTable(),
      {"email": "ab<c.def@ghi.com"}.toTable(),
      {"email": "abc.de<f@ghi.com"}.toTable(),
      {"email": ".email@domain.com"}.toTable(),
      {"email": "email.@domain.com"}.toTable(),
      {"email": "email..email@domain.com"}.toTable(),
      {"email": "あいうえお@domain.com"}.toTable(),
      {"email": "email@-domain.com"}.toTable(),
      {"email": "email@-.-.-.-"}.toTable(),
      {"email": "email@123.123.123.123"}.toTable(),
      {"email": "abc.def@ghi.#%&'/=~`*+?{}^$-|"}.toTable(),
      {"email": "abc.def@gh<i.com"}.toTable(),
      {"email": "abc.def@ghi.co<m"}.toTable(),
      {"email": "a@0"}.toTable(),
      {"email": "a@0.0"}.toTable(),
      {"email": ""}.toTable(),
      {"email": "a@a.0"}.toTable(),
      {"email": "a@.a"}.toTable(),
      {"email": "a@a-.a"}.toTable(),
      {"email": "a@-a.a"}.toTable(),
      {"email": "email@domain..com"}.toTable(),
      {"email": ""}.toTable(),
      {"email": ""}.toTable(),
      # {"email": ""}.toTable(),
      # {"email": ""}.toTable(),
      # {"email": ""}.toTable(),
      # {"email": ""}.toTable(),
      # {"email": ""}.toTable(),
      # {"email": ""}.toTable(),
      # {"email": ""}.toTable(),
      # {"email": ""}.toTable(),
      # {"email": ""}.toTable(),
      # {"email": ""}.toTable(),
      # {"email": ""}.toTable(),
      # {"email": ""}.toTable(),
      # {"email": ""}.toTable(),
      # {"email": ""}.toTable(),
      # {"email": ""}.toTable(),
      # {"email": ""}.toTable(),
      # {"email": ""}.toTable(),
      # {"email": ""}.toTable(),
      # {"email": ""}.toTable(),
      # {"email": ""}.toTable(),
      # {"email": ""}.toTable(),
      # {"email": ""}.toTable(),
      # {"email": ""}.toTable(),
      # {"email": ""}.toTable(),
      # {"email": ""}.toTable(),
      # {"email": ""}.toTable(),
      # {"email": ""}.toTable(),
      # {"email": ""}.toTable(),
      # {"email": ""}.toTable(),
      # {"email": ""}.toTable(),
      # {"email": ""}.toTable(),
      # {"email": ""}.toTable(),
    ]

    for valid_address in valid_addresses:
      let v = Validation(params: valid_address,
                          errors: newJObject())
                        .strictEmail("email")
      check v.errors.len > 0