/* Generated by the Nim Compiler v1.6.8 */
var framePtr = null;
var excHandler = 0;
var lastJSError = null;
if (!Math.trunc) {
  Math.trunc = function(v) {
    v = +v;
    if (!isFinite(v)) return v;
    return (v - v % 1) || (v < 0 ? -0 : v === 0 ? v : 0);
  };
}

var objectID_1073741986 = [0];

function main() {
    
function createScene_889192487(canvas_889192488, engine_889192489) {
      var result_889192490 = null;

      BeforeRet: do {
        var scene_889192505 = (new BABYLON.Scene((engine_889192489)));
        var camera_889192583 = (new BABYLON.ArcRotateCamera(("camera"), (-1.5707963267948966), (1.2566370614359172), (3), ((new BABYLON.Vector3((0), (0), (0)))), (scene_889192505)));
        camera_889192583.attachControl((canvas_889192488), (true));
        var light_889192658 = (new BABYLON.HemisphericLight(("light"), ((new BABYLON.Vector3((0), (1), (0)))), (scene_889192505)));
        var box_889192691 = (new BABYLON.MeshBuilder.CreateBox(("box"), ({}), (scene_889192505)));
        result_889192490 = scene_889192505;
        break BeforeRet;
      } while (false);

      return result_889192490;

    }
    
function HEX3Aanonymous_889192693() {
        scene_889192692.render();

      
    }

    var canvas_889192458 = document.getElementById("renderCanvas");
    var engine_889192486 = (new BABYLON.Engine((canvas_889192458)));
    var scene_889192692 = createScene_889192487(canvas_889192458, engine_889192486);
    engine_889192486.runRenderLoop((HEX3Aanonymous_889192693));

  
}
