[framework]
name = "basolato"

[main]
urls.plaintext = "/plaintext"
urls.json = "/json"
urls.db = "/db"
urls.query = "/queries?queries="
urls.fortune = "/fortunes"
urls.update = "/updates?queries="
urls.cached_query = "/cached-queries?count="
approach = "Realistic"
classification = "Fullstack"
database = "postgres"
database_os = "Linux"
os = "Linux"
orm = "Full"
platform = "httpbeast"
webserver = "None"
versus = "jester"
